services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=not-a-secret
      - BEARER_TOKEN=secret
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - SMTP_FROM=no-reply@example.com
      - SMTP_USER=""
      - SMTP_PASS=""
      - APP_ORIGIN=http://localhost:8080
      - LITESTREAM_ACCESS_KEY_ID=test
      - LITESTREAM_SECRET_ACCESS_KEY=test
      - LITESTREAM_ENDPOINT=http://s3mock:9090
      - LITESTREAM_BUCKET=litestream
    depends_on:
      mailpit:
        condition: service_started
      s3mock:
        condition: service_started
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    ports:
      - "1080:8025"
      - "1025:1025"
    restart: unless-stopped

  s3mock:
    image: adobe/s3mock:latest
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=litestream
    ports:
      - "9090:9090"
    restart: unless-stopped
